"""create_tickets_messages

Revision ID: 32dee88efc8a
Revises: 2f018d8c993e
Create Date: 2026-03-31 11:57:55.841490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dee88efc8a'
down_revision: Union[str, None] = '2f018d8c993e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_ticket_id', table_name='messages')
    op.alter_column('tickets', 'subject',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tickets', 'requester_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tickets', 'requester_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tickets', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('ix_tickets_org_id', table_name='tickets')
    op.drop_index('ix_tickets_session_id', table_name='tickets')
    op.drop_index('ix_tickets_status', table_name='tickets')
    op.drop_constraint('tickets_org_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_assigned_to_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'tickets', 'organisations', ['org_id'], ['id'])
    op.drop_column('tickets', 'needs_human')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('needs_human', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_assigned_to_fkey', 'tickets', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tickets_org_id_fkey', 'tickets', 'organisations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_tickets_status', 'tickets', ['status'], unique=False)
    op.create_index('ix_tickets_session_id', 'tickets', ['session_id'], unique=False)
    op.create_index('ix_tickets_org_id', 'tickets', ['org_id'], unique=False)
    op.alter_column('tickets', 'session_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tickets', 'requester_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tickets', 'requester_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tickets', 'subject',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.create_index('ix_messages_ticket_id', 'messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###
