"""Add ticket fields to Organisation

Revision ID: 5804dca740a4
Revises: cf0bdb703951
Create Date: 2026-04-28 11:50:58.303693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5804dca740a4'
down_revision: Union[str, None] = 'cf0bdb703951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('available_tickets', sa.Integer(), server_default='100', nullable=False))
    op.add_column('organisations', sa.Column('total_tickets_used', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'total_tickets_used')
    op.drop_column('organisations', 'available_tickets')
    # ### end Alembic commands ###
