"""add_ticket_batches

Revision ID: c6585f6e4426
Revises: 5804dca740a4
Create Date: 2026-04-28 12:40:58.785454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6585f6e4426'
down_revision: Union[str, None] = '5804dca740a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('initial_tickets', sa.Integer(), nullable=False),
    sa.Column('remaining_tickets', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Data Migration: Move existing balances into a new TicketBatch
    op.execute("""
        INSERT INTO ticket_batches (id, org_id, initial_tickets, remaining_tickets, created_at)
        SELECT gen_random_uuid(), id, available_tickets, available_tickets, now()
        FROM organisations
        WHERE available_tickets > 0
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_batches')
    # ### end Alembic commands ###
