"""Add subscription_ends_at

Revision ID: e5aaa7fe1191
Revises: a719c288dcf1
Create Date: 2026-04-13 12:10:41.930454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5aaa7fe1191'
down_revision: Union[str, None] = 'a719c288dcf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'subscription_ends_at')
    # ### end Alembic commands ###
